### ISSUE TITLE
Suggest Support Weapon adjust "Slave Zero X: Episode Enyo "

### ISSUE THREAD

**Issue by ni1chigo2115** [codeflorist/quakespasm-openvr#6]
Recently, id officially started to distribute Slave Zero X: Episode Enyo, an external episode of Slave Zero X, as an add-on for Quake in collaboration with Slave Zero X.
This is an excellent TC for Quake that also works with vanilla Quake.
(It borrows some audio data from Quake, so you need the original Quake data to run it.)

Of course, it also worked with quakespasm-openvr, but the size of the weapon is large compared to the real size, and the size, position, and angle of the weapon needs to be adjusted. (This is especially tricky in Slave Zero X: Episode Enyo, since the weapon placement is on the right side of the screen, like a typical FPS.)

https://poppyworks.itch.io/episode-enyo

**Comment by codeflorist** [comment]
Hey @ni1chigo2115,

That's definitely a good idea. I'll add support, once i have the time.

(If you want to and have the time, you can find the fitting values by modifying the vr_wofs* cvars in console as described here:
https://github.com/gameflorist/quakespasm-openvr?tab=readme-ov-file#note-about-weapons.)

**Comment by codeflorist** [comment]
hey @ni1chigo2115!

i've just released 0.96.1c. it includes support for "Slave Zero X: Episode Enyo" - as well as [Block-Quake](https://kebby-quake.itch.io/block-quake). have fun!

**Comment by ni1chigo2115** [comment]
https://twitter.com/ni1chigo2115/status/1767522607413494083
finework !!
Thanks for doing me a favor!
Let's just try to get to the end of this one for now ...
